pbsync/pbsync.py: rework config parser func to raise informative exception
In case some config option is missing in the PBSync.xml the error that you
get is just "Config exception: 'NoneType' object has no attribute 'text'"

This change reworks the pbsync_config_parser_func() function to throw an
exception detailing which keys are missing.

The error now looks more in the form of:
```
Config exception: 'Missing keys: git/gcmversion, git/gcmversionsuffix, git/gcmsuffix'
ERROR:root:PBSync.xml config file is not valid or not found. Please check the integrity of the file
```

Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>